[project]
name = "testpythonqcm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "lxml>=5.3.1",
    "pillow>=11.1.0",
    "prettyprint>=0.1.5",
    "pygments>=2.19.1",
]
